export const coachProfiles = [
  {
    id: 'C-001',
    name: 'RABINDRANATH SARKAR',
    role: 'HEAD COACH',
    specialty: 'CRICKET',
    experience: '15+ YEARS',
    status: 'ACTIVE',
    email: 'rabindra@ars-academy.com',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    batches: 4,
    aadhaarNumber: 'XXXX XXXX 1234',
    license: 'BCCI LEVEL 3',
    image: 'RS',
    personal: {
      dob: '14 Feb 1986',
    },
    contact: {
      address: 'Daladali Chowk, Ranchi, Jharkhand',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834001',
    },
    professional: {
      role: 'Head Coach',
      specialty: 'Cricket',
      experience: '15+ Years',
      license: 'BCCI Level 3',
    },
    assignedBatches: ['Elite Morning Cricket', 'Pro Evening Session', 'Weekend Performance Camp'],
    documents: ['Aadhaar', 'PAN', 'Qualification', 'Sports Certificate', 'Experience Certificate', 'Police Verification'],
    statusDetail: 'Active',
  },
  {
    id: 'C-002',
    name: 'ANKITA MUKHERJEE',
    role: 'SENIOR COACH',
    specialty: 'BADMINTON',
    experience: '8 YEARS',
    status: 'ON LEAVE',
    email: 'ankita@ars-academy.com',
    phone: '+91 98765 12345',
    whatsapp: '+91 98765 12345',
    batches: 3,
    aadhaarNumber: 'XXXX XXXX 5678',
    license: 'BAI CERTIFIED',
    image: 'AM',
    personal: {
      dob: '22 Aug 1990',
    },
    contact: {
      address: 'Morabadi, Ranchi, Jharkhand',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834008',
    },
    professional: {
      role: 'Senior Coach',
      specialty: 'Badminton',
      experience: '8 Years',
      license: 'BAI Certified',
    },
    assignedBatches: ['Junior Shuttle Program', 'Skill Development Unit'],
    documents: ['Aadhaar', 'PAN', 'Qualification', 'Sports Certificate', 'Medical Fitness'],
    statusDetail: 'On Leave',
  },
  {
    id: 'C-003',
    name: 'SUSHANT SINGH',
    role: 'FIELD COACH',
    specialty: 'FOOTBALL',
    experience: '5 YEARS',
    status: 'ACTIVE',
    email: 'sushant@ars-academy.com',
    phone: '+91 98765 67890',
    whatsapp: '+91 98765 67890',
    batches: 5,
    aadhaarNumber: 'XXXX XXXX 9012',
    license: 'AIFF LEVEL D',
    image: 'SS',
    personal: {
      dob: '09 Nov 1994',
    },
    contact: {
      address: 'Kanke Road, Ranchi, Jharkhand',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834006',
    },
    professional: {
      role: 'Field Coach',
      specialty: 'Football',
      experience: '5 Years',
      license: 'AIFF Level D',
    },
    assignedBatches: ['Junior Football Ops', 'Development Unit'],
    documents: ['Aadhaar', 'PAN', 'Qualification', 'Police Verification', 'Resume / CV'],
    statusDetail: 'Active',
  },
  {
    id: 'C-004',
    name: 'PRIYA DAS',
    role: 'JUNIOR COACH',
    specialty: 'CRICKET',
    experience: '3 YEARS',
    status: 'ACTIVE',
    email: 'priya@ars-academy.com',
    phone: '+91 98765 00000',
    whatsapp: '+91 98765 00000',
    batches: 2,
    aadhaarNumber: 'XXXX XXXX 3456',
    license: 'STATE LEVEL',
    image: 'PD',
    personal: {
      dob: '18 May 1998',
    },
    contact: {
      address: 'Hatia, Ranchi, Jharkhand',
      city: 'Ranchi',
      state: 'Jharkhand',
      pinCode: '834003',
    },
    professional: {
      role: 'Junior Coach',
      specialty: 'Cricket',
      experience: '3 Years',
      license: 'State Level',
    },
    assignedBatches: ['U-14 Girls Cricket', 'Foundation Skills Camp'],
    documents: ['Aadhaar', 'PAN', 'Qualification', 'Medical Fitness', 'Resume / CV'],
    statusDetail: 'Active',
  },
];

export const getCoachProfileById = (coachId) => coachProfiles.find((coach) => coach.id === coachId) ?? null;